"""Initial schema - users, trips, pois, itinerary

Revision ID: 001
Revises: 
Create Date: 2025-10-21

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    
    # Create users table
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    
    # Create trips table
    op.create_table('trips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('destination_lat', sa.Float(), nullable=True),
    sa.Column('destination_lng', sa.Float(), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_index(op.f('ix_trips_created_at'), 'trips', ['created_at'], unique=False)
    
    # Create pois table
    op.create_table('pois',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('formatted_address', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('user_ratings_total', sa.Integer(), nullable=True),
    sa.Column('price_level', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=False),
    sa.Column('cache_expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pois_place_id'), 'pois', ['place_id'], unique=True)
    
    # Create trip_pois table
    op.create_table('trip_pois',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('poi_id', sa.Integer(), nullable=False),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('recommendation_reason', sa.Text(), nullable=True),
    sa.Column('user_selected', sa.Boolean(), nullable=False),
    sa.Column('user_rejected', sa.Boolean(), nullable=False),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['pois.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_pois_trip_id'), 'trip_pois', ['trip_id'], unique=False)
    op.create_index(op.f('ix_trip_pois_poi_id'), 'trip_pois', ['poi_id'], unique=False)
    
    # Create itinerary_items table
    op.create_table('itinerary_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('poi_id', sa.Integer(), nullable=True),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('visit_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('travel_time_to_next_minutes', sa.Integer(), nullable=True),
    sa.Column('travel_leg', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['pois.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itinerary_items_trip_id'), 'itinerary_items', ['trip_id'], unique=False)
    op.create_index(op.f('ix_itinerary_items_poi_id'), 'itinerary_items', ['poi_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f('ix_itinerary_items_poi_id'), table_name='itinerary_items')
    op.drop_index(op.f('ix_itinerary_items_trip_id'), table_name='itinerary_items')
    op.drop_table('itinerary_items')
    
    op.drop_index(op.f('ix_trip_pois_poi_id'), table_name='trip_pois')
    op.drop_index(op.f('ix_trip_pois_trip_id'), table_name='trip_pois')
    op.drop_table('trip_pois')
    
    op.drop_index(op.f('ix_pois_place_id'), table_name='pois')
    op.drop_table('pois')
    
    op.drop_index(op.f('ix_trips_created_at'), table_name='trips')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_table('trips')
    
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

















